# Generated by Django 5.1.7 on 2025-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('SUPERUSER', 'SUPERUSER'), ('RESP', 'RESP')], default='RESP', max_length=9)),
                ('avatar', models.ImageField(default='avatars/default.jpg', null=True, upload_to='avatars/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
