# Generated by Django 5.1.7 on 2025-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='shops_images/')),
                ('responsible_id', models.ManyToManyField(to='accounts.user')),
            ],
        ),
    ]
